using System.Reflection;
[assembly: AssemblyTitle("Dipper")]
[assembly: AssemblyDescription("Sharp# gopher browser.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("Dipper")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.19.902.1536")]
